const fs = require('fs');

const locales = fs
    .readdirSync(__dirname + '/i18n/')
    .filter((name) => name.endsWith('.json'))
    .map((name) => name.slice(0, -'.json'.length))
    .sort();

const [basename] = __filename.split('/').reverse();

code = `
// WARNING: This file is generated by ${basename}. Please do not modify it directly (including formatting).
export const locales: string[] = ${JSON.stringify(locales, undefined, 4)};
`;

fs.writeFileSync(__dirname + '/src/locales.ts', Buffer.from(code));
