import type { Category } from '@prezly/sdk';

/**
 * This story data is pulled from The Good Newsroom
 */
export const CATEGORIES: Category[] = [
    {
        id: 4880,
        display_name: 'Environment',
        display_description: '',
        stories_number: 5,
        public_stories_number: 5,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Environment',
                description: '',
                slug: 'environment',
                public_stories_number: 2,
            },
            en_GB: {
                locale: {
                    code: 'en_GB',
                    locale: 'en_GB',
                    name: 'English (United Kingdom)',
                    native_name: 'English (United Kingdom)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en_GB',
                        name: 'English (United Kingdom)',
                    },
                },
                name: 'Environment',
                description: '',
                slug: 'environment',
                public_stories_number: 3,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 4876,
        display_name: 'Food',
        display_description: '',
        stories_number: 5,
        public_stories_number: 5,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Food',
                description: '',
                slug: 'food',
                public_stories_number: 2,
            },
            en_GB: {
                locale: {
                    code: 'en_GB',
                    locale: 'en_GB',
                    name: 'English (United Kingdom)',
                    native_name: 'English (United Kingdom)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en_GB',
                        name: 'English (United Kingdom)',
                    },
                },
                name: 'Food',
                description: '',
                slug: 'food',
                public_stories_number: 2,
            },
            nl_BE: {
                locale: {
                    code: 'nl_BE',
                    locale: 'nl_BE',
                    name: 'Dutch (Belgium)',
                    native_name: 'Nederlands (België)',
                    direction: 'ltr' as any,
                    language_code: 'nl',
                    language: {
                        code: 'nl_BE',
                        name: 'Dutch (Belgium)',
                    },
                },
                name: 'Eten',
                description: '',
                slug: 'eten',
                public_stories_number: 1,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 5986,
        display_name: 'Technology',
        display_description:
            "Scientific breakthroughs that show the future isn't all doom and Skynet.",
        stories_number: 3,
        public_stories_number: 3,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Technology',
                description:
                    "Scientific breakthroughs that show the future isn't all doom and Skynet.",
                slug: 'technology',
                public_stories_number: 2,
            },
            nl_BE: {
                locale: {
                    code: 'nl_BE',
                    locale: 'nl_BE',
                    name: 'Dutch (Belgium)',
                    native_name: 'Nederlands (België)',
                    direction: 'ltr' as any,
                    language_code: 'nl',
                    language: {
                        code: 'nl_BE',
                        name: 'Dutch (Belgium)',
                    },
                },
                name: 'Technologie',
                description:
                    'Wetenschappelijke doorbraken die de toekomst laten zien is niet alleen maar onheil en Skynet.',
                slug: 'technologie',
                public_stories_number: 1,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 5987,
        display_name: 'Art',
        display_description: 'Developments from the global art scene.',
        stories_number: 2,
        public_stories_number: 2,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Art',
                description: 'Developments from the global art scene.',
                slug: 'art',
                public_stories_number: 2,
            },
            nl_BE: {
                locale: {
                    code: 'nl_BE',
                    locale: 'nl_BE',
                    name: 'Dutch (Belgium)',
                    native_name: 'Nederlands (België)',
                    direction: 'ltr' as any,
                    language_code: 'nl',
                    language: {
                        code: 'nl_BE',
                        name: 'Dutch (Belgium)',
                    },
                },
                name: 'Kunst',
                description: '',
                slug: 'kunst',
                public_stories_number: 0,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 6602,
        display_name: 'Games',
        display_description: '',
        stories_number: 1,
        public_stories_number: 1,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Games',
                description: '',
                slug: 'games',
                public_stories_number: 1,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 6603,
        display_name: 'Animals',
        display_description: '',
        stories_number: 1,
        public_stories_number: 1,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Animals',
                description: '',
                slug: 'animals',
                public_stories_number: 1,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 6604,
        display_name: 'Sports',
        display_description: '',
        stories_number: 1,
        public_stories_number: 1,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Sports',
                description: '',
                slug: 'sports',
                public_stories_number: 1,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 6605,
        display_name: 'Other',
        display_description: '',
        stories_number: 1,
        public_stories_number: 1,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Other',
                description: '',
                slug: 'other',
                public_stories_number: 1,
            },
        },
        is_featured: false,
        image: null,
    },
    {
        id: 6606,
        display_name: 'Family',
        display_description: '',
        stories_number: 1,
        public_stories_number: 1,
        i18n: {
            en: {
                locale: {
                    code: 'en',
                    locale: 'en',
                    name: 'English (Global)',
                    native_name: 'English (Global)',
                    direction: 'ltr' as any,
                    language_code: 'en',
                    language: {
                        code: 'en',
                        name: 'English (Global)',
                    },
                },
                name: 'Family',
                description: '',
                slug: 'family',
                public_stories_number: 1,
            },
        },
        is_featured: false,
        image: null,
    },
];
