const fs = require('fs');

const locales = fs
    .readdirSync(__dirname + '/i18n/')
    .filter((name) => name.endsWith('.json'))
    .map((name) => name.slice(0, -'.json'.length))
    .sort();

const [basename] = __filename.split('/').reverse();

process.stdout.write(`
/**
 * @generated This code is generated by ${basename}.
 *            Please do not modify it directly (including formatting).
 */

import type { Locale } from './Locale';

export const supportedLocales: Locale.IsoCode[] = ${JSON.stringify(locales, undefined, 4)};
`);
