# Workflow name
name: 'Chromatic Publish'

# Event for the workflow
on: push

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# List of jobs
jobs:
    chromatic:
        # Operating System
        runs-on: ubuntu-latest

        # Job steps
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # 👈 Required to retrieve git history

            - uses: pnpm/action-setup@v2
              name: Install PNPM
              id: pnpm-install
              with:
                  version: 8
                  run_install: false
            
            - name: Get pnpm store directory
              shell: bash
              run: |
                echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                path: ${{ env.STORE_PATH }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm build

            - name: Install ui dependencies
              working-directory: ./packages/ui
              run: pnpm install

            - name: Install Chromatic
              run: pnpm add -D chromatic

            #👇 Adds Chromatic as a step in the workflow
            - uses: chromaui/action@v1
              name: Run Chromatic
              # Options required for Chromatic's GitHub Action
              with:
                  #👇 Chromatic projectToken,
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  workingDir: ./packages/ui # 👈 Working directory for the Chromatic CLI
                  exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
                  skip: '@(renovate/**|dependabot/**)' # 👈 Option to skip Chromatic builds for PRs created by Renovate and Dependabot
                  onlyChanged: true # 👈 Enable TurboSnap (only update snapshots for changed files)
                  externals: |
                      - '/styles/**'

